#!/usr/bin/env bash

#
# @author Ari Setiawan
# @create 15.10-2023 23:39
# @github https://github.com/hxAri/Yutiriti
#
# Yūtiriti Copyright (c) 2023 - Ari Setiawan <hxari@proton.me>
# Yūtiriti Licence under GNU General Public Licence v3
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

clear

if [[ -f /usr/bin/pip || -f /usr/local/bin/pip ]]; then
	installed=$( pip list | grep yutiriti )
	if [[ $installed != "" ]]; then
		pip uninstall yutiriti -y
	fi
	python setup.py install
else
	echo -e "yutiriti: pip: does not installed" && exit 1
fi
