#!/usr/bin/env bash

# Clear terminal screen
clear

# Run Pylint
pylint \
	--argument-naming-style=camelCase \
	--attr-naming-style=camelCase \
	--class-attribute-naming-style=UPPER_CASE \
	--class-const-naming-style=UPPER_CASE \
	--class-naming-style=PascalCase \
	--const-naming-style=UPPER_CASE \
	--variable-naming-style=camelCase \
	--function-naming-style=camelCase \
	--max-attributes=30 \
	--method-naming-style=camelCase \
	--good-names="e,i,id,u" \
	--ignore-docstrings=y \
	--ignore-long-lines="[^\\n]+" \
	--indent-string="    " \
	--disable=broad-exception-caught \
	--disable=consider-using-f-string \
	--disable=function-redefined \
	--disable=keyword-arg-before-vararg \
	--disable=missing-function-docstring \
	--disable=missing-module-docstring \
	--disable=multiple-statements \
	--disable=redefined-argument-from-local \
	--disable=redefined-builtin \
	--disable=redefined-outer-name \
	--disable=too-many-arguments \
	--disable=too-many-branches \
	--disable=too-many-lines \
	--disable=too-many-locals \
	--disable=too-many-nested-blocks \
	--disable=too-many-statements \
	--disable=super-init-not-called \
	--disable=trailing-newlines \
	--disable=trailing-whitespace \
	--disable=unnecessary-dunder-call \
	--disable=unnecessary-pass \
	--disable=unexpected-special-method-signature \
	src/yutiriti/*.py