
name: Pylint

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --argument-naming-style=camelCase --attr-naming-style=camelCase --class-attribute-naming-style=UPPER_CASE --class-const-naming-style=UPPER_CASE --class-naming-style=PascalCase --const-naming-style=UPPER_CASE --variable-naming-style=camelCase --function-naming-style=camelCase --max-attributes=30 --method-naming-style=camelCase --good-names="e,i,u" --ignore-docstrings=y --ignore-long-lines="[^\\n]+" --indent-string="    " --disable=broad-exception-caught --disable=consider-using-f-string --disable=function-redefined --disable=keyword-arg-before-vararg --disable=missing-function-docstring --disable=missing-module-docstring --disable=multiple-statements --disable=redefined-argument-from-local --disable=redefined-builtin --disable=redefined-outer-name --disable=too-many-arguments --disable=too-many-branches --disable=too-many-locals --disable=too-many-nested-blocks --disable=too-many-statements --disable=trailing-newlines --disable=trailing-whitespace --disable=unnecessary-dunder-call --disable=unnecessary-pass --disable=unexpected-special-method-signature src/yutiriti/*.py 
  